// Default settings
// Separated from settings model since they need to be accessed by both main and window processes
export const defaults = {
	fontSize: 13,
	compact: false,
	theme: 'os' as 'os' | 'light' | 'dark',
	showProfileTabs: true,
	profilesGridColumns: 12,
	notificationsOverlaySize: 3,
	beepOnOperationError: false,
	appUpdatesCheckingInterval: 20,
	pluginUpdatesCheckingInterval: 168,
	nodeUpdatesCheckingInterval: 720,
	taskbarButton: true,
	taskbarProgress: true,
	trayIcon: false,
	minimizeToTray: false,
	closeToTray: false,
	alwaysOnTop: false,
	compactImportCodes: true,
	operationsProcessPriority: 'NORMAL' as ProcessPriority,
	operationsHistoryLimit: 1000,
	outputsHistoryLimit: 1000,
	operationLogLimit: 100000,
	expandStagingLogs: 'error',
	developerMode: false,
	editCommand: 'code "${path}"',

	updateChannel: 'stable' as 'stable' | 'beta',
	lastAppUpdatesCheckTime: 0,
	lastNodeUpdatesCheckTime: 0,
	lastPluginUpdatesCheckTime: 0,
	openDevTools: false,
	globalOutputsDrawerHeight: 0,
	profileOutputsDrawerHeight: 0,
	stagingBarHeight: 0.3,
	profileCategory: '',

	warnNonOfficialInstall: true,
	warnExternalInstall: true,
	warnProfileImport: true,
};
